import { FastifyInstance } from "fastify";
import { prisma } from "../lib/prisma";
import { requireRoles } from "../lib/rbac";
import {
  aiProvider,
  logAiUsage,
  GenerationOutputType,
  PresentationTemplate,
  PresentationContent,
  ActivityGroupSize,
  ACTIVITY_GROUP_SIZE_LABELS,
  ACTIVITY_RESOURCE_OPTIONS,
} from "../lib/ai";
import { hasSufficientCredits, getFeatureCost } from "../lib/credits";
import { storage } from "../lib/storage";
import { extractPdfPageRangeText } from "../lib/extraction";
import { buildPresentationPptx } from "../lib/pptxExport";
import { ContextSource } from "@prisma/client";

const MAX_CONTEXT_CHARS_FOR_PROMPT = 12000;

export interface SourceSelection {
  contextSourceId: string;
  pageFrom?: number;
  pageTo?: number;
}

// Replaces "use every extracted source on the topic" with "use exactly what
// the teacher picked for this generation" - a topic accumulates sources
// across many sessions, most of them irrelevant to any single output.
async function resolveSelectedContextText(
  contextSources: ContextSource[],
  selection: SourceSelection[]
): Promise<{ contextText: string | null; usedSources: ContextSource[] }> {
  const byId = new Map(contextSources.map((s) => [s.id, s]));
  const parts: string[] = [];
  const usedSources: ContextSource[] = [];

  for (const sel of selection) {
    const source = byId.get(sel.contextSourceId);
    if (!source) continue;

    if (source.sourceType === "pdf" && sel.pageFrom && sel.pageTo && source.fileLocation) {
      try {
        const buffer = await storage.readBuffer(source.fileLocation);
        const result = await extractPdfPageRangeText(buffer, sel.pageFrom, sel.pageTo);
        if (result && result.text) {
          parts.push(result.text);
          usedSources.push(source);
          continue;
        }
      } catch {
        // Fall through to the stored full-document text below rather than
        // dropping the source entirely over a page-range extraction hiccup.
      }
    }

    if (source.extractionStatus === "extracted" && source.extractedText) {
      parts.push(source.extractedText);
      usedSources.push(source);
    }
  }

  if (parts.length === 0) return { contextText: null, usedSources: [] };
  const combined = parts.join("\n\n---\n\n").slice(0, MAX_CONTEXT_CHARS_FOR_PROMPT);
  return { contextText: combined, usedSources };
}

async function getSchoolFormatTemplate(schoolId: string) {
  return prisma.schoolFormatTemplate.findUnique({
    where: { schoolId_appliesTo: { schoolId, appliesTo: "generation" } },
  });
}

// Applies presentation-only work beyond what the AI call itself produces -
// branding (logo/colors) and the footer credit line are rendering concerns
// (set from the school's row and the requesting teacher, never generated by
// the model), applied independently of which content template was chosen.
// No-op for every other outputType. Presentations no longer use stock photos
// at all - there is no image-fetching step here any more.
async function applyPresentationTemplateExtras(params: {
  content: string;
  outputType: GenerationOutputType;
  schoolId: string;
  teacherUserId: string;
  // Per-generation color tweak - overrides the school's saved branding
  // colors for this deck only, without touching the saved branding row.
  overridePrimaryColor?: string;
  overrideSecondaryColor?: string;
}): Promise<string> {
  if (params.outputType !== "presentation") return params.content;

  let parsed: { slides?: { title: string; bullets: string[] }[]; [key: string]: unknown };
  try {
    parsed = JSON.parse(params.content);
  } catch {
    return params.content;
  }

  const [school, teacher] = await Promise.all([
    prisma.school.findUnique({ where: { id: params.schoolId }, select: { name: true, logoUrl: true, primaryColor: true, secondaryColor: true } }),
    prisma.appUser.findUnique({ where: { id: params.teacherUserId }, select: { fullName: true } }),
  ]);

  const primaryColor = params.overridePrimaryColor ?? school?.primaryColor ?? null;
  const secondaryColor = params.overrideSecondaryColor ?? school?.secondaryColor ?? null;
  if (primaryColor || secondaryColor || school?.logoUrl) {
    parsed.logoUrl = school?.logoUrl ?? null;
    parsed.primaryColor = primaryColor;
    parsed.secondaryColor = secondaryColor;
  }

  if (teacher?.fullName && school?.name) {
    parsed.footerLabel = `Prepared by ${teacher.fullName} · ${school.name}`;
  }

  return JSON.stringify(parsed);
}

const VALID_OUTPUT_TYPES: GenerationOutputType[] = [
  "lesson_plan",
  "custom_activity_report",
  "flashcards",
  "presentation",
];
const VALID_MODES = ["plan", "generate"];
const VALID_PRESENTATION_TEMPLATES: PresentationTemplate[] = ["detailed", "instructional", "school_format", "more_visual"];
const VALID_ACTIVITY_GROUP_SIZES = Object.keys(ACTIVITY_GROUP_SIZE_LABELS) as ActivityGroupSize[];
const VALID_ACTIVITY_RESOURCES = ACTIVITY_RESOURCE_OPTIONS.map((r) => r.key);
const HEX_COLOR_RE = /^#[0-9a-f]{6}$/i;

interface CreateGenerationBody {
  outputType: GenerationOutputType;
  mode?: string;
  classCount?: number;
  minutesPerClass?: number;
  language?: string;
  customPrompt?: string;
  // Only meaningful when outputType is "presentation".
  presentationTemplate?: string;
  // Per-generation color tweak - overrides the school's saved branding
  // colors for this deck only. Omit to just use the saved branding as-is.
  overridePrimaryColor?: string;
  overrideSecondaryColor?: string;
  // Which context sources (and, for a long PDF, which page range) to ground
  // this generation in. Empty/omitted means "no context" - not "everything",
  // that implicit-everything behavior is what this field replaces.
  sources?: SourceSelection[];
  // Only meaningful when outputType is "custom_activity_report".
  activityGroupSize?: string;
  activityResources?: string[];
}

interface UpdateGenerationBody {
  editedOutput: string;
}

const scoped = (app: FastifyInstance) => [app.authenticate, app.requireSchoolScope, requireRoles("teacher")];

export async function generationRoutes(app: FastifyInstance) {
  app.post<{ Params: { id: string }; Body: CreateGenerationBody }>(
    "/topics/:id/generations",
    { onRequest: scoped(app) },
    async (request, reply) => {
      const body = request.body ?? ({} as CreateGenerationBody);

      if (!body.outputType || !VALID_OUTPUT_TYPES.includes(body.outputType)) {
        return reply.code(400).send({
          data: null,
          error: { code: "validation_error", message: `outputType must be one of ${VALID_OUTPUT_TYPES.join(", ")}` },
        });
      }
      const mode = body.mode ?? "generate";
      if (!VALID_MODES.includes(mode)) {
        return reply.code(400).send({
          data: null,
          error: { code: "validation_error", message: `mode must be one of ${VALID_MODES.join(", ")}` },
        });
      }
      if (body.presentationTemplate && !VALID_PRESENTATION_TEMPLATES.includes(body.presentationTemplate as PresentationTemplate)) {
        return reply.code(400).send({
          data: null,
          error: { code: "validation_error", message: `presentationTemplate must be one of ${VALID_PRESENTATION_TEMPLATES.join(", ")}` },
        });
      }
      if (body.overridePrimaryColor && !HEX_COLOR_RE.test(body.overridePrimaryColor)) {
        return reply.code(400).send({ data: null, error: { code: "validation_error", message: "overridePrimaryColor must be a hex color like #4C4CE0" } });
      }
      if (body.overrideSecondaryColor && !HEX_COLOR_RE.test(body.overrideSecondaryColor)) {
        return reply.code(400).send({ data: null, error: { code: "validation_error", message: "overrideSecondaryColor must be a hex color like #4C4CE0" } });
      }
      if (body.activityGroupSize && !VALID_ACTIVITY_GROUP_SIZES.includes(body.activityGroupSize as ActivityGroupSize)) {
        return reply.code(400).send({
          data: null,
          error: { code: "validation_error", message: `activityGroupSize must be one of ${VALID_ACTIVITY_GROUP_SIZES.join(", ")}` },
        });
      }
      if (body.activityResources?.some((key) => !VALID_ACTIVITY_RESOURCES.includes(key as (typeof VALID_ACTIVITY_RESOURCES)[number]))) {
        return reply.code(400).send({
          data: null,
          error: { code: "validation_error", message: `activityResources must only contain: ${VALID_ACTIVITY_RESOURCES.join(", ")}` },
        });
      }

      const topic = await prisma.topic.findFirst({
        where: { id: request.params.id, schoolId: request.schoolId },
        include: { classSection: true, contextSources: true },
      });
      if (!topic) {
        return reply.code(404).send({ data: null, error: { code: "not_found", message: "Topic not found" } });
      }

      const { contextText, usedSources } = await resolveSelectedContextText(topic.contextSources, body.sources ?? []);
      const formatTemplate = await getSchoolFormatTemplate(request.schoolId);

      const classCount = body.classCount ?? 1;
      const minutesPerClass = body.minutesPerClass ?? 45;
      if (classCount > 10 || minutesPerClass > 90) {
        return reply.code(400).send({
          data: null,
          error: { code: "validation_error", message: "classCount must be <= 10 and minutesPerClass <= 90" },
        });
      }

      if (!(await hasSufficientCredits(request.user.sub, getFeatureCost("generation")))) {
        return reply.code(400).send({ data: null, error: { code: "insufficient_credits", message: "Not enough credits to generate this content" } });
      }

      const start = Date.now();
      let content: string;
      let model: string;
      let generationStatus = "succeeded";
      try {
        const result = await aiProvider.generateContent({
          topicName: topic.name,
          subject: topic.subject,
          board: topic.board,
          outputType: body.outputType,
          classCount,
          minutesPerClass,
          language: body.language ?? "English",
          customPrompt: body.customPrompt ?? null,
          classLabel: `${topic.classSection.className} ${topic.classSection.sectionName}`,
          contextText,
          schoolFormatInstructions: formatTemplate?.templateBody ?? null,
          presentationTemplate: body.presentationTemplate as PresentationTemplate | undefined,
          activityGroupSize: body.activityGroupSize as ActivityGroupSize | undefined,
          activityResources: body.activityResources,
        });
        content = await applyPresentationTemplateExtras({
          content: result.content,
          outputType: body.outputType,
          schoolId: request.schoolId,
          teacherUserId: request.user.sub,
          overridePrimaryColor: body.overridePrimaryColor,
          overrideSecondaryColor: body.overrideSecondaryColor,
        });
        model = result.model;
      } catch (err) {
        app.log.error(err, "Generation failed");
        const failed = await prisma.generation.create({
          data: {
            topicId: topic.id,
            teacherUserId: request.user.sub,
            outputType: body.outputType,
            mode,
            classCount,
            minutesPerClass,
            language: body.language ?? "English",
            customPrompt: body.customPrompt ?? null,
            activityGroupSize: body.activityGroupSize ?? null,
            activityResources: body.activityResources ?? [],
            aiOutput: "",
            modelUsed: "unknown",
            generationStatus: "failed",
          },
          include: { contextSources: true },
        });
        return reply.code(201).send({ data: failed, meta: {} });
      }

      const generation = await prisma.generation.create({
        data: {
          topicId: topic.id,
          teacherUserId: request.user.sub,
          outputType: body.outputType,
          activityGroupSize: body.activityGroupSize ?? null,
          activityResources: body.activityResources ?? [],
          mode,
          classCount,
          minutesPerClass,
          language: body.language ?? "English",
          customPrompt: body.customPrompt ?? null,
          aiOutput: content,
          modelUsed: model,
          generationStatus,
          contextSources: { connect: usedSources.map((s) => ({ id: s.id })) },
          selectedSources: (body.sources ?? []) as unknown as object,
          schoolFormatTemplateId: formatTemplate?.id ?? null,
        },
        include: {
          contextSources: true,
          topic: { select: { name: true, subject: true, board: true, classSection: { select: { className: true, sectionName: true } } } },
        },
      });

      await logAiUsage({
        schoolId: request.schoolId,
        teacherUserId: request.user.sub,
        feature: "generation",
        model,
        durationMs: Date.now() - start,
      });

      return reply.code(201).send({ data: generation, meta: {} });
    }
  );

  app.get<{ Params: { id: string } }>("/generations/:id", { onRequest: scoped(app) }, async (request, reply) => {
    const generation = await prisma.generation.findFirst({
      where: { id: request.params.id, topic: { schoolId: request.schoolId } },
      include: {
        contextSources: true,
        topic: { select: { name: true, subject: true, board: true, classSection: { select: { className: true, sectionName: true } } } },
      },
    });
    if (!generation) {
      return reply.code(404).send({ data: null, error: { code: "not_found", message: "Generation not found" } });
    }
    return { data: generation, meta: {} };
  });

  // Real, downloadable .pptx - generated on demand from whatever the teacher
  // is currently looking at (editedOutput once they've edited it, matching
  // the "editedOutput is authoritative everywhere once set" convention - see
  // schema.prisma's Generation model), not cached/stored, so it always
  // reflects the latest edit for free and needs no export-log table.
  app.get<{ Params: { id: string } }>("/generations/:id/export.pptx", { onRequest: scoped(app) }, async (request, reply) => {
    const generation = await prisma.generation.findFirst({
      where: { id: request.params.id, topic: { schoolId: request.schoolId } },
      include: { topic: { select: { name: true } } },
    });
    if (!generation) {
      return reply.code(404).send({ data: null, error: { code: "not_found", message: "Generation not found" } });
    }
    if (generation.outputType !== "presentation") {
      return reply.code(400).send({ data: null, error: { code: "validation_error", message: "Only presentations can be exported to PPTX" } });
    }

    let content: PresentationContent;
    try {
      content = JSON.parse(generation.editedOutput ?? generation.aiOutput);
    } catch {
      return reply.code(500).send({ data: null, error: { code: "invalid_content", message: "Stored presentation content is not valid JSON" } });
    }
    if (!Array.isArray(content.slides)) {
      return reply.code(500).send({ data: null, error: { code: "invalid_content", message: "Stored presentation content has no slides" } });
    }

    const buffer = await buildPresentationPptx(content, generation.topic.name);
    const safeName = generation.topic.name.replace(/[^a-z0-9]+/gi, "-").toLowerCase().slice(0, 60) || "presentation";
    reply.header("Content-Type", "application/vnd.openxmlformats-officedocument.presentationml.presentation");
    reply.header("Content-Disposition", `attachment; filename="${safeName}.pptx"`);
    return reply.send(buffer);
  });

  app.patch<{ Params: { id: string }; Body: UpdateGenerationBody }>(
    "/generations/:id",
    { onRequest: scoped(app) },
    async (request, reply) => {
      const body = request.body ?? ({} as UpdateGenerationBody);
      if (!body.editedOutput || !body.editedOutput.trim()) {
        return reply.code(400).send({ data: null, error: { code: "validation_error", message: "editedOutput is required" } });
      }

      const generation = await prisma.generation.findFirst({
        where: { id: request.params.id, topic: { schoolId: request.schoolId } },
      });
      if (!generation) {
        return reply.code(404).send({ data: null, error: { code: "not_found", message: "Generation not found" } });
      }

      const updated = await prisma.generation.update({
        where: { id: generation.id },
        data: { editedOutput: body.editedOutput },
        include: { contextSources: true },
      });

      return { data: updated, meta: {} };
    }
  );

  app.post<{ Params: { id: string } }>("/generations/:id/retry", { onRequest: scoped(app) }, async (request, reply) => {
    const generation = await prisma.generation.findFirst({
      where: { id: request.params.id, topic: { schoolId: request.schoolId } },
      include: { topic: { include: { classSection: true, contextSources: true } }, contextSources: true },
    });
    if (!generation) {
      return reply.code(404).send({ data: null, error: { code: "not_found", message: "Generation not found" } });
    }

    // Reuse exactly what the original generation used - not the topic's
    // current full source list, so retrying doesn't silently pull in sources
    // added since. Generations created before source selection existed have
    // no selectedSources; fall back to the sources relation (whole documents,
    // no page ranges - that detail wasn't tracked pre-selection).
    const selection: SourceSelection[] =
      (generation.selectedSources as unknown as SourceSelection[] | null) ??
      generation.contextSources.map((s) => ({ contextSourceId: s.id }));
    const { contextText, usedSources } = await resolveSelectedContextText(generation.topic.contextSources, selection);
    const formatTemplate = await getSchoolFormatTemplate(request.schoolId);

    // Preserve the teacher's chosen presentation style (and any per-deck
    // color tweak) across a retry rather than silently reverting to
    // defaults - parsed from whatever this generation last produced (falls
    // back to defaults for pre-template rows).
    let presentationTemplate: PresentationTemplate | undefined;
    let overridePrimaryColor: string | undefined;
    let overrideSecondaryColor: string | undefined;
    if (generation.outputType === "presentation") {
      try {
        const previous = JSON.parse(generation.editedOutput ?? generation.aiOutput) as {
          template?: PresentationTemplate;
          primaryColor?: string;
          secondaryColor?: string;
        };
        presentationTemplate = previous.template;
        overridePrimaryColor = previous.primaryColor;
        overrideSecondaryColor = previous.secondaryColor;
      } catch {
        // Ignore - defaults apply below.
      }
    }

    if (!(await hasSufficientCredits(request.user.sub, getFeatureCost("generation")))) {
      return reply.code(400).send({ data: null, error: { code: "insufficient_credits", message: "Not enough credits to retry this generation" } });
    }

    const start = Date.now();
    const result = await aiProvider.generateContent({
      topicName: generation.topic.name,
      subject: generation.topic.subject,
      board: generation.topic.board,
      outputType: generation.outputType as GenerationOutputType,
      classCount: generation.classCount ?? 1,
      minutesPerClass: generation.minutesPerClass ?? 45,
      language: generation.language,
      customPrompt: generation.customPrompt,
      classLabel: `${generation.topic.classSection.className} ${generation.topic.classSection.sectionName}`,
      contextText,
      schoolFormatInstructions: formatTemplate?.templateBody ?? null,
      presentationTemplate,
      activityGroupSize: (generation.activityGroupSize as ActivityGroupSize | null) ?? undefined,
      activityResources: generation.activityResources,
    });
    const content = await applyPresentationTemplateExtras({
      content: result.content,
      outputType: generation.outputType as GenerationOutputType,
      schoolId: request.schoolId,
      teacherUserId: request.user.sub,
      overridePrimaryColor,
      overrideSecondaryColor,
    });
    const model = result.model;

    const updated = await prisma.generation.update({
      where: { id: generation.id },
      data: {
        aiOutput: content,
        modelUsed: model,
        generationStatus: "succeeded",
        editedOutput: null,
        contextSources: { set: usedSources.map((s) => ({ id: s.id })) },
        selectedSources: selection as unknown as object,
        schoolFormatTemplateId: formatTemplate?.id ?? null,
      },
      include: {
        contextSources: true,
        topic: { select: { name: true, subject: true, board: true, classSection: { select: { className: true, sectionName: true } } } },
      },
    });

    await logAiUsage({
      schoolId: request.schoolId,
      teacherUserId: request.user.sub,
      feature: "generation",
      model,
      durationMs: Date.now() - start,
    });

    return { data: updated, meta: {} };
  });

  // Publishing/unpublishing is what actually gates /student/materials - see
  // shareStatus on the Generation model. This is distinct from a future
  // "push to Communication Hub" delivery feature, which doesn't exist yet.
  app.post<{ Params: { id: string } }>("/generations/:id/publish", { onRequest: scoped(app) }, async (request, reply) => {
    const generation = await prisma.generation.findFirst({
      where: { id: request.params.id, topic: { schoolId: request.schoolId } },
    });
    if (!generation) {
      return reply.code(404).send({ data: null, error: { code: "not_found", message: "Generation not found" } });
    }
    if (generation.generationStatus !== "succeeded") {
      return reply.code(400).send({ data: null, error: { code: "validation_error", message: "Only a succeeded generation can be shared with students" } });
    }
    const updated = await prisma.generation.update({
      where: { id: generation.id },
      data: { shareStatus: "published", publishedAt: new Date() },
      include: { contextSources: true },
    });
    return { data: updated, meta: {} };
  });

  app.post<{ Params: { id: string } }>("/generations/:id/unpublish", { onRequest: scoped(app) }, async (request, reply) => {
    const generation = await prisma.generation.findFirst({
      where: { id: request.params.id, topic: { schoolId: request.schoolId } },
    });
    if (!generation) {
      return reply.code(404).send({ data: null, error: { code: "not_found", message: "Generation not found" } });
    }
    const updated = await prisma.generation.update({
      where: { id: generation.id },
      data: { shareStatus: "draft", publishedAt: null },
      include: { contextSources: true },
    });
    return { data: updated, meta: {} };
  });
}
