import { FastifyInstance } from "fastify";
import { prisma } from "../lib/prisma";
import { requireRoles } from "../lib/rbac";
import {
  aiProvider,
  logAiUsage,
  GenerationOutputType,
  PresentationTemplate,
  PresentationContent,
  ActivityGroupSize,
  ACTIVITY_GROUP_SIZE_LABELS,
  ACTIVITY_RESOURCE_OPTIONS,
  LEARNING_STAGE_OPTIONS,
} from "../lib/ai";
import { hasSufficientCredits, getFeatureCost } from "../lib/credits";
import { storage } from "../lib/storage";
import { extractPdfPageRangeText } from "../lib/extraction";
import { buildPresentationPptx } from "../lib/pptxExport";
import { getSchoolBoard } from "../lib/boards";
import type { MediaItem } from "../lib/media";
import { EmbedSelection, applyMedia, assemblePresentation, buildMediaItems, catalogFor, loadMediaAssets, mediaItemsFromContent } from "../lib/generation-media";
import { ContextSource } from "@prisma/client";

const MAX_CONTEXT_CHARS_FOR_PROMPT = 12000;

export interface SourceSelection {
  contextSourceId: string;
  pageFrom?: number;
  pageTo?: number;
}

// Replaces "use every extracted source on the topic" with "use exactly what
// the teacher picked for this generation" - a topic accumulates sources
// across many sessions, most of them irrelevant to any single output.
async function resolveSelectedContextText(
  contextSources: ContextSource[],
  selection: SourceSelection[]
): Promise<{ contextText: string | null; usedSources: ContextSource[] }> {
  const byId = new Map(contextSources.map((s) => [s.id, s]));
  const parts: string[] = [];
  const usedSources: ContextSource[] = [];

  for (const sel of selection) {
    const source = byId.get(sel.contextSourceId);
    if (!source) continue;

    if (source.sourceType === "pdf" && sel.pageFrom && sel.pageTo && source.fileLocation) {
      try {
        const buffer = await storage.readBuffer(source.fileLocation);
        const result = await extractPdfPageRangeText(buffer, sel.pageFrom, sel.pageTo);
        if (result && result.text) {
          parts.push(result.text);
          usedSources.push(source);
          continue;
        }
      } catch {
        // Fall through to the stored full-document text below rather than
        // dropping the source entirely over a page-range extraction hiccup.
      }
    }

    if (source.extractionStatus === "extracted" && source.extractedText) {
      parts.push(source.extractedText);
      usedSources.push(source);
    }
  }

  if (parts.length === 0) return { contextText: null, usedSources: [] };
  const combined = parts.join("\n\n---\n\n").slice(0, MAX_CONTEXT_CHARS_FOR_PROMPT);
  return { contextText: combined, usedSources };
}

async function getSchoolFormatTemplate(schoolId: string) {
  return prisma.schoolFormatTemplate.findUnique({
    where: { schoolId_appliesTo: { schoolId, appliesTo: "generation" } },
  });
}

// Applies presentation-only work beyond what the AI call itself produces -
// branding (logo/colors) and the footer credit line are rendering concerns
// (set from the school's row and the requesting teacher, never generated by
// the model), applied independently of which content template was chosen.
// No-op for every other outputType. Presentations no longer use stock photos
// at all - there is no image-fetching step here any more.
async function applyPresentationTemplateExtras(params: {
  content: string;
  outputType: GenerationOutputType;
  schoolId: string;
  teacherUserId: string;
  // Per-generation color tweak - overrides the school's saved branding
  // colors for this deck only, without touching the saved branding row.
  overridePrimaryColor?: string;
  overrideSecondaryColor?: string;
}): Promise<string> {
  if (params.outputType !== "presentation") return params.content;

  let parsed: { slides?: { title: string; bullets: string[] }[]; [key: string]: unknown };
  try {
    parsed = JSON.parse(params.content);
  } catch {
    return params.content;
  }

  const [school, teacher] = await Promise.all([
    prisma.school.findUnique({ where: { id: params.schoolId }, select: { name: true, logoUrl: true, primaryColor: true, secondaryColor: true } }),
    prisma.appUser.findUnique({ where: { id: params.teacherUserId }, select: { fullName: true } }),
  ]);

  const primaryColor = params.overridePrimaryColor ?? school?.primaryColor ?? null;
  const secondaryColor = params.overrideSecondaryColor ?? school?.secondaryColor ?? null;
  if (primaryColor || secondaryColor || school?.logoUrl) {
    parsed.logoUrl = school?.logoUrl ?? null;
    parsed.primaryColor = primaryColor;
    parsed.secondaryColor = secondaryColor;
  }

  if (teacher?.fullName && school?.name) {
    parsed.footerLabel = `Prepared by ${teacher.fullName} · ${school.name}`;
  }

  return JSON.stringify(parsed);
}

const VALID_OUTPUT_TYPES: GenerationOutputType[] = [
  "lesson_plan",
  "custom_activity_report",
  "flashcards",
  "presentation",
];
const VALID_MODES = ["plan", "generate"];
const VALID_PRESENTATION_TEMPLATES: PresentationTemplate[] = ["detailed", "instructional", "school_format", "more_visual"];
const VALID_ACTIVITY_GROUP_SIZES = Object.keys(ACTIVITY_GROUP_SIZE_LABELS) as ActivityGroupSize[];
const VALID_ACTIVITY_RESOURCES = ACTIVITY_RESOURCE_OPTIONS.map((r) => r.key);
const VALID_LEARNING_STAGES = LEARNING_STAGE_OPTIONS as readonly string[];
const HEX_COLOR_RE = /^#[0-9a-f]{6}$/i;

interface CreateGenerationBody {
  outputType: GenerationOutputType;
  mode?: string;
  classCount?: number;
  minutesPerClass?: number;
  language?: string;
  customPrompt?: string;
  // Only meaningful when outputType is "presentation".
  presentationTemplate?: string;
  // Per-generation color tweak - overrides the school's saved branding
  // colors for this deck only. Omit to just use the saved branding as-is.
  overridePrimaryColor?: string;
  overrideSecondaryColor?: string;
  // Which context sources (and, for a long PDF, which page range) to ground
  // this generation in. Empty/omitted means "no context" - not "everything",
  // that implicit-everything behavior is what this field replaces.
  sources?: SourceSelection[];
  // Uploaded/researched images and PDF pages to show as-is in the output
  // (instead of the AI re-creating them). Independent of `sources`, which only
  // feeds text to the model.
  embeds?: EmbedSelection[];
  // Presentation only: build the deck purely from `embeds` with no AI call -
  // free, since nothing is generated.
  assembleOnly?: boolean;
  // Only meaningful when outputType is "custom_activity_report".
  activityGroupSize?: string;
  activityResources?: string[];
  learningStages?: string[];
}

// A retried deck asks for the same items again: turn what the previous
// content attached back into the selection shape (one entry per source, page
// range spanning what was shown).
function selectionFromMedia(items: MediaItem[]): EmbedSelection[] {
  const bySource = new Map<string, EmbedSelection>();
  for (const item of items) {
    const existing = bySource.get(item.sourceId);
    if (!existing) {
      bySource.set(item.sourceId, item.page ? { contextSourceId: item.sourceId, pageFrom: item.page, pageTo: item.page } : { contextSourceId: item.sourceId });
    } else if (item.page) {
      existing.pageFrom = Math.min(existing.pageFrom ?? item.page, item.page);
      existing.pageTo = Math.max(existing.pageTo ?? item.page, item.page);
    }
  }
  return [...bySource.values()];
}

interface UpdateGenerationBody {
  editedOutput: string;
}

interface SessionProgressBody {
  session: number;
  completed: boolean;
}

const scoped = (app: FastifyInstance) => [app.authenticate, app.requireSchoolScope, requireRoles("teacher")];

export async function generationRoutes(app: FastifyInstance) {
  app.post<{ Params: { id: string }; Body: CreateGenerationBody }>(
    "/topics/:id/generations",
    { onRequest: scoped(app) },
    async (request, reply) => {
      const body = request.body ?? ({} as CreateGenerationBody);

      if (!body.outputType || !VALID_OUTPUT_TYPES.includes(body.outputType)) {
        return reply.code(400).send({
          data: null,
          error: { code: "validation_error", message: `outputType must be one of ${VALID_OUTPUT_TYPES.join(", ")}` },
        });
      }
      const mode = body.mode ?? "generate";
      if (!VALID_MODES.includes(mode)) {
        return reply.code(400).send({
          data: null,
          error: { code: "validation_error", message: `mode must be one of ${VALID_MODES.join(", ")}` },
        });
      }
      if (body.presentationTemplate && !VALID_PRESENTATION_TEMPLATES.includes(body.presentationTemplate as PresentationTemplate)) {
        return reply.code(400).send({
          data: null,
          error: { code: "validation_error", message: `presentationTemplate must be one of ${VALID_PRESENTATION_TEMPLATES.join(", ")}` },
        });
      }
      if (body.overridePrimaryColor && !HEX_COLOR_RE.test(body.overridePrimaryColor)) {
        return reply.code(400).send({ data: null, error: { code: "validation_error", message: "overridePrimaryColor must be a hex color like #4C4CE0" } });
      }
      if (body.overrideSecondaryColor && !HEX_COLOR_RE.test(body.overrideSecondaryColor)) {
        return reply.code(400).send({ data: null, error: { code: "validation_error", message: "overrideSecondaryColor must be a hex color like #4C4CE0" } });
      }
      if (body.activityGroupSize && !VALID_ACTIVITY_GROUP_SIZES.includes(body.activityGroupSize as ActivityGroupSize)) {
        return reply.code(400).send({
          data: null,
          error: { code: "validation_error", message: `activityGroupSize must be one of ${VALID_ACTIVITY_GROUP_SIZES.join(", ")}` },
        });
      }
      if (body.activityResources?.some((key) => !VALID_ACTIVITY_RESOURCES.includes(key as (typeof VALID_ACTIVITY_RESOURCES)[number]))) {
        return reply.code(400).send({
          data: null,
          error: { code: "validation_error", message: `activityResources must only contain: ${VALID_ACTIVITY_RESOURCES.join(", ")}` },
        });
      }
      if (body.learningStages?.some((stage) => !VALID_LEARNING_STAGES.includes(stage))) {
        return reply.code(400).send({
          data: null,
          error: { code: "validation_error", message: `learningStages must only contain: ${VALID_LEARNING_STAGES.join(", ")}` },
        });
      }

      const topic = await prisma.topic.findFirst({
        where: { id: request.params.id, schoolId: request.schoolId },
        include: { classSection: true, contextSources: true },
      });
      if (!topic) {
        return reply.code(404).send({ data: null, error: { code: "not_found", message: "Topic not found" } });
      }

      const { contextText, usedSources } = await resolveSelectedContextText(topic.contextSources, body.sources ?? []);
      const formatTemplate = await getSchoolFormatTemplate(request.schoolId);

      const classCount = body.classCount ?? 1;
      const minutesPerClass = body.minutesPerClass ?? 45;
      if (classCount > 10 || minutesPerClass > 90) {
        return reply.code(400).send({
          data: null,
          error: { code: "validation_error", message: "classCount must be <= 10 and minutesPerClass <= 90" },
        });
      }

      let mediaItems: MediaItem[] = [];
      let mediaCatalog: ReturnType<typeof catalogFor> | undefined;
      if (body.embeds && body.embeds.length > 0) {
        const built = buildMediaItems(topic.contextSources, body.embeds);
        if ("error" in built) {
          return reply.code(400).send({ data: null, error: { code: "validation_error", message: built.error } });
        }
        mediaItems = built.items;
        mediaCatalog = catalogFor(built.items, built.descriptions);
      }
      const assembleOnly = body.assembleOnly === true;
      if (assembleOnly && (body.outputType !== "presentation" || mediaItems.length === 0)) {
        return reply.code(400).send({
          data: null,
          error: { code: "validation_error", message: "assembleOnly needs a presentation and at least one image or PDF page to use as-is" },
        });
      }
      const embeddedSources = topic.contextSources.filter((s) => mediaItems.some((item) => item.sourceId === s.id));

      // Assembling from the teacher's own media makes no AI call, so it is free.
      if (!assembleOnly && !(await hasSufficientCredits(request.user.sub, await getFeatureCost("generation")))) {
        return reply.code(400).send({ data: null, error: { code: "insufficient_credits", message: "Not enough credits to generate this content" } });
      }

      const start = Date.now();
      let content: string;
      let model: string;
      let generationStatus = "succeeded";
      try {
        const classLabel = `${topic.classSection.className} ${topic.classSection.sectionName}`;
        if (assembleOnly) {
          content = await applyPresentationTemplateExtras({
            content: assemblePresentation({ topicName: topic.name, subtitle: `${topic.subject} · ${classLabel}`, items: mediaItems }),
            outputType: body.outputType,
            schoolId: request.schoolId,
            teacherUserId: request.user.sub,
            overridePrimaryColor: body.overridePrimaryColor,
            overrideSecondaryColor: body.overrideSecondaryColor,
          });
          model = "assembled";
        } else {
          const result = await aiProvider.generateContent({
            topicName: topic.name,
            subject: topic.subject,
            board: await getSchoolBoard(request.schoolId),
            outputType: body.outputType,
            classCount,
            minutesPerClass,
            language: body.language ?? "English",
            customPrompt: body.customPrompt ?? null,
            classLabel,
            contextText,
            schoolFormatInstructions: formatTemplate?.templateBody ?? null,
            presentationTemplate: body.presentationTemplate as PresentationTemplate | undefined,
            activityGroupSize: body.activityGroupSize as ActivityGroupSize | undefined,
            activityResources: body.activityResources,
            learningStages: body.learningStages,
            mediaCatalog,
          });
          content = await applyPresentationTemplateExtras({
            content: applyMedia(result.content, body.outputType, mediaItems),
            outputType: body.outputType,
            schoolId: request.schoolId,
            teacherUserId: request.user.sub,
            overridePrimaryColor: body.overridePrimaryColor,
            overrideSecondaryColor: body.overrideSecondaryColor,
          });
          model = result.model;
        }
      } catch (err) {
        app.log.error(err, "Generation failed");
        const failed = await prisma.generation.create({
          data: {
            topicId: topic.id,
            teacherUserId: request.user.sub,
            outputType: body.outputType,
            mode,
            classCount,
            minutesPerClass,
            language: body.language ?? "English",
            customPrompt: body.customPrompt ?? null,
            activityGroupSize: body.activityGroupSize ?? null,
            activityResources: body.activityResources ?? [],
            learningStages: body.learningStages ?? [],
            aiOutput: "",
            modelUsed: "unknown",
            generationStatus: "failed",
          },
          include: { contextSources: true },
        });
        return reply.code(201).send({ data: failed, meta: {} });
      }

      const generation = await prisma.generation.create({
        data: {
          topicId: topic.id,
          teacherUserId: request.user.sub,
          outputType: body.outputType,
          activityGroupSize: body.activityGroupSize ?? null,
          activityResources: body.activityResources ?? [],
          learningStages: body.learningStages ?? [],
          mode,
          classCount,
          minutesPerClass,
          language: body.language ?? "English",
          customPrompt: body.customPrompt ?? null,
          aiOutput: content,
          modelUsed: model,
          generationStatus,
          // Sources used as text context plus the ones shown as-is - both are
          // "what this generation is based on".
          contextSources: { connect: [...new Map([...usedSources, ...embeddedSources].map((s) => [s.id, { id: s.id }])).values()] },
          selectedSources: (body.sources ?? []) as unknown as object,
          schoolFormatTemplateId: formatTemplate?.id ?? null,
        },
        include: {
          contextSources: true,
          topic: { select: { name: true, subject: true, classSection: { select: { className: true, sectionName: true } } } },
        },
      });

      if (!assembleOnly) {
        await logAiUsage({
          schoolId: request.schoolId,
          teacherUserId: request.user.sub,
          feature: "generation",
          model,
          durationMs: Date.now() - start,
        });
      }

      return reply.code(201).send({ data: generation, meta: {} });
    }
  );

  app.get<{ Params: { id: string } }>("/generations/:id", { onRequest: scoped(app) }, async (request, reply) => {
    const generation = await prisma.generation.findFirst({
      where: { id: request.params.id, topic: { schoolId: request.schoolId } },
      include: {
        contextSources: true,
        topic: { select: { name: true, subject: true, classSection: { select: { className: true, sectionName: true } } } },
      },
    });
    if (!generation) {
      return reply.code(404).send({ data: null, error: { code: "not_found", message: "Generation not found" } });
    }
    return { data: generation, meta: {} };
  });

  // Real, downloadable .pptx - generated on demand from whatever the teacher
  // is currently looking at (editedOutput once they've edited it, matching
  // the "editedOutput is authoritative everywhere once set" convention - see
  // schema.prisma's Generation model), not cached/stored, so it always
  // reflects the latest edit for free and needs no export-log table.
  app.get<{ Params: { id: string } }>("/generations/:id/export.pptx", { onRequest: scoped(app) }, async (request, reply) => {
    const generation = await prisma.generation.findFirst({
      where: { id: request.params.id, topic: { schoolId: request.schoolId } },
      include: { topic: { select: { name: true } } },
    });
    if (!generation) {
      return reply.code(404).send({ data: null, error: { code: "not_found", message: "Generation not found" } });
    }
    if (generation.outputType !== "presentation") {
      return reply.code(400).send({ data: null, error: { code: "validation_error", message: "Only presentations can be exported to PPTX" } });
    }

    let content: PresentationContent;
    try {
      content = JSON.parse(generation.editedOutput ?? generation.aiOutput);
    } catch {
      return reply.code(500).send({ data: null, error: { code: "invalid_content", message: "Stored presentation content is not valid JSON" } });
    }
    if (!Array.isArray(content.slides)) {
      return reply.code(500).send({ data: null, error: { code: "invalid_content", message: "Stored presentation content has no slides" } });
    }

    const buffer = await buildPresentationPptx(content, generation.topic.name, await loadMediaAssets(generation.topicId, content));
    const safeName = generation.topic.name.replace(/[^a-z0-9]+/gi, "-").toLowerCase().slice(0, 60) || "presentation";
    reply.header("Content-Type", "application/vnd.openxmlformats-officedocument.presentationml.presentation");
    reply.header("Content-Disposition", `attachment; filename="${safeName}.pptx"`);
    return reply.send(buffer);
  });

  app.patch<{ Params: { id: string }; Body: UpdateGenerationBody }>(
    "/generations/:id",
    { onRequest: scoped(app) },
    async (request, reply) => {
      const body = request.body ?? ({} as UpdateGenerationBody);
      if (!body.editedOutput || !body.editedOutput.trim()) {
        return reply.code(400).send({ data: null, error: { code: "validation_error", message: "editedOutput is required" } });
      }

      const generation = await prisma.generation.findFirst({
        where: { id: request.params.id, topic: { schoolId: request.schoolId } },
      });
      if (!generation) {
        return reply.code(404).send({ data: null, error: { code: "not_found", message: "Generation not found" } });
      }

      const updated = await prisma.generation.update({
        where: { id: generation.id },
        data: { editedOutput: body.editedOutput },
        include: { contextSources: true },
      });

      return { data: updated, meta: {} };
    }
  );

  // Teacher-reported "I taught class period N" progress for a lesson plan
  // spanning multiple classes (classCount > 1) - separate from whether the
  // content itself was edited, and never auto-closes the topic.
  app.post<{ Params: { id: string }; Body: SessionProgressBody }>(
    "/generations/:id/session-progress",
    { onRequest: scoped(app) },
    async (request, reply) => {
      const body = request.body ?? ({} as SessionProgressBody);
      if (typeof body.session !== "number" || typeof body.completed !== "boolean") {
        return reply.code(400).send({ data: null, error: { code: "validation_error", message: "session (number) and completed (boolean) are required" } });
      }

      const generation = await prisma.generation.findFirst({
        where: { id: request.params.id, topic: { schoolId: request.schoolId } },
      });
      if (!generation) {
        return reply.code(404).send({ data: null, error: { code: "not_found", message: "Generation not found" } });
      }

      const completedSessions = body.completed
        ? [...new Set([...generation.completedSessions, body.session])].sort((a, b) => a - b)
        : generation.completedSessions.filter((s) => s !== body.session);

      const updated = await prisma.generation.update({
        where: { id: generation.id },
        data: { completedSessions },
        include: { contextSources: true },
      });

      return { data: updated, meta: {} };
    }
  );

  app.post<{ Params: { id: string } }>("/generations/:id/retry", { onRequest: scoped(app) }, async (request, reply) => {
    const generation = await prisma.generation.findFirst({
      where: { id: request.params.id, topic: { schoolId: request.schoolId } },
      include: { topic: { include: { classSection: true, contextSources: true } }, contextSources: true },
    });
    if (!generation) {
      return reply.code(404).send({ data: null, error: { code: "not_found", message: "Generation not found" } });
    }

    // Reuse exactly what the original generation used - not the topic's
    // current full source list, so retrying doesn't silently pull in sources
    // added since. Generations created before source selection existed have
    // no selectedSources; fall back to the sources relation (whole documents,
    // no page ranges - that detail wasn't tracked pre-selection).
    const selection: SourceSelection[] =
      (generation.selectedSources as unknown as SourceSelection[] | null) ??
      generation.contextSources.map((s) => ({ contextSourceId: s.id }));
    const { contextText, usedSources } = await resolveSelectedContextText(generation.topic.contextSources, selection);
    const formatTemplate = await getSchoolFormatTemplate(request.schoolId);

    // Preserve the teacher's chosen presentation style (and any per-deck
    // color tweak) across a retry rather than silently reverting to
    // defaults - parsed from whatever this generation last produced (falls
    // back to defaults for pre-template rows).
    let presentationTemplate: PresentationTemplate | undefined;
    let overridePrimaryColor: string | undefined;
    let overrideSecondaryColor: string | undefined;
    if (generation.outputType === "presentation") {
      try {
        const previous = JSON.parse(generation.editedOutput ?? generation.aiOutput) as {
          template?: PresentationTemplate;
          primaryColor?: string;
          secondaryColor?: string;
        };
        presentationTemplate = previous.template;
        overridePrimaryColor = previous.primaryColor;
        overrideSecondaryColor = previous.secondaryColor;
      } catch {
        // Ignore - defaults apply below.
      }
    }

    // Put the same images / PDF pages back, from whatever the previous output
    // attached - skipping any whose source has since been deleted.
    const stillThere = new Set(generation.topic.contextSources.map((s) => s.id));
    const previousMedia = mediaItemsFromContent(generation.aiOutput).filter((item) => stillThere.has(item.sourceId));
    let mediaItems: MediaItem[] = [];
    let mediaCatalog: ReturnType<typeof catalogFor> | undefined;
    if (previousMedia.length > 0) {
      const built = buildMediaItems(generation.topic.contextSources, selectionFromMedia(previousMedia));
      if (!("error" in built)) {
        mediaItems = built.items;
        mediaCatalog = catalogFor(built.items, built.descriptions);
      }
    }
    const embeddedSources = generation.topic.contextSources.filter((s) => mediaItems.some((item) => item.sourceId === s.id));
    // A deck assembled purely from the teacher's media has no AI step to redo.
    const wasAssembled = generation.modelUsed === "assembled" && mediaItems.length > 0;

    if (!wasAssembled && !(await hasSufficientCredits(request.user.sub, await getFeatureCost("generation")))) {
      return reply.code(400).send({ data: null, error: { code: "insufficient_credits", message: "Not enough credits to retry this generation" } });
    }

    const start = Date.now();
    const classLabel = `${generation.topic.classSection.className} ${generation.topic.classSection.sectionName}`;
    let rawContent: string;
    let model: string;
    if (wasAssembled) {
      rawContent = assemblePresentation({ topicName: generation.topic.name, subtitle: `${generation.topic.subject} · ${classLabel}`, items: mediaItems });
      model = "assembled";
    } else {
      const result = await aiProvider.generateContent({
        topicName: generation.topic.name,
        subject: generation.topic.subject,
        board: await getSchoolBoard(request.schoolId),
        outputType: generation.outputType as GenerationOutputType,
        classCount: generation.classCount ?? 1,
        minutesPerClass: generation.minutesPerClass ?? 45,
        language: generation.language,
        customPrompt: generation.customPrompt,
        classLabel,
        contextText,
        schoolFormatInstructions: formatTemplate?.templateBody ?? null,
        presentationTemplate,
        activityGroupSize: (generation.activityGroupSize as ActivityGroupSize | null) ?? undefined,
        activityResources: generation.activityResources,
        learningStages: generation.learningStages,
        mediaCatalog,
      });
      rawContent = applyMedia(result.content, generation.outputType, mediaItems);
      model = result.model;
    }
    const content = await applyPresentationTemplateExtras({
      content: rawContent,
      outputType: generation.outputType as GenerationOutputType,
      schoolId: request.schoolId,
      teacherUserId: request.user.sub,
      overridePrimaryColor,
      overrideSecondaryColor,
    });

    const updated = await prisma.generation.update({
      where: { id: generation.id },
      data: {
        aiOutput: content,
        modelUsed: model,
        generationStatus: "succeeded",
        editedOutput: null,
        contextSources: { set: [...new Map([...usedSources, ...embeddedSources].map((s) => [s.id, { id: s.id }])).values()] },
        selectedSources: selection as unknown as object,
        schoolFormatTemplateId: formatTemplate?.id ?? null,
      },
      include: {
        contextSources: true,
        topic: { select: { name: true, subject: true, classSection: { select: { className: true, sectionName: true } } } },
      },
    });

    if (!wasAssembled) {
      await logAiUsage({
        schoolId: request.schoolId,
        teacherUserId: request.user.sub,
        feature: "generation",
        model,
        durationMs: Date.now() - start,
      });
    }

    return { data: updated, meta: {} };
  });

  // Publishing/unpublishing is what actually gates /student/materials - see
  // shareStatus on the Generation model. This is distinct from a future
  // "push to Communication Hub" delivery feature, which doesn't exist yet.
  // studentStubIds omitted or empty = shared with the whole class (the
  // default, unchanged behavior); a non-empty list narrows it to just them.
  app.post<{ Params: { id: string }; Body: { studentStubIds?: string[] } }>(
    "/generations/:id/publish",
    { onRequest: scoped(app) },
    async (request, reply) => {
      const generation = await prisma.generation.findFirst({
        where: { id: request.params.id, topic: { schoolId: request.schoolId } },
        include: { topic: { select: { classSectionId: true } } },
      });
      if (!generation) {
        return reply.code(404).send({ data: null, error: { code: "not_found", message: "Generation not found" } });
      }
      if (generation.generationStatus !== "succeeded") {
        return reply.code(400).send({ data: null, error: { code: "validation_error", message: "Only a succeeded generation can be shared with students" } });
      }

      const studentStubIds = [...new Set(request.body?.studentStubIds ?? [])];
      const sharedWithAll = studentStubIds.length === 0;
      if (!sharedWithAll) {
        const validCount = await prisma.studentStub.count({
          where: { id: { in: studentStubIds }, classSectionId: generation.topic.classSectionId, status: "active" },
        });
        if (validCount !== studentStubIds.length) {
          return reply.code(400).send({ data: null, error: { code: "validation_error", message: "One or more selected students aren't in this topic's class" } });
        }
      }

      const updated = await prisma.generation.update({
        where: { id: generation.id },
        data: { shareStatus: "published", publishedAt: new Date(), sharedWithAll, sharedStudentStubIds: sharedWithAll ? [] : studentStubIds },
        include: { contextSources: true },
      });
      return { data: updated, meta: {} };
    }
  );

  app.post<{ Params: { id: string } }>("/generations/:id/unpublish", { onRequest: scoped(app) }, async (request, reply) => {
    const generation = await prisma.generation.findFirst({
      where: { id: request.params.id, topic: { schoolId: request.schoolId } },
    });
    if (!generation) {
      return reply.code(404).send({ data: null, error: { code: "not_found", message: "Generation not found" } });
    }
    const updated = await prisma.generation.update({
      where: { id: generation.id },
      data: { shareStatus: "draft", publishedAt: null },
      include: { contextSources: true },
    });
    return { data: updated, meta: {} };
  });
}
