import { FastifyInstance } from "fastify";
import { prisma } from "../lib/prisma";
import { requireRoles } from "../lib/rbac";
import { aiProvider, logAiUsage, GenerationOutputType, PresentationTemplate, PresentationColorScheme } from "../lib/ai";
import { hasSufficientCredits, getFeatureCost } from "../lib/credits";
import { storage } from "../lib/storage";
import { extractPdfPageRangeText } from "../lib/extraction";
import { searchUnsplashPhoto, downloadImage } from "../lib/unsplash";
import { ContextSource } from "@prisma/client";

const MAX_CONTEXT_CHARS_FOR_PROMPT = 12000;

export interface SourceSelection {
  contextSourceId: string;
  pageFrom?: number;
  pageTo?: number;
}

// Replaces "use every extracted source on the topic" with "use exactly what
// the teacher picked for this generation" - a topic accumulates sources
// across many sessions, most of them irrelevant to any single output.
async function resolveSelectedContextText(
  contextSources: ContextSource[],
  selection: SourceSelection[]
): Promise<{ contextText: string | null; usedSources: ContextSource[] }> {
  const byId = new Map(contextSources.map((s) => [s.id, s]));
  const parts: string[] = [];
  const usedSources: ContextSource[] = [];

  for (const sel of selection) {
    const source = byId.get(sel.contextSourceId);
    if (!source) continue;

    if (source.sourceType === "pdf" && sel.pageFrom && sel.pageTo && source.fileLocation) {
      try {
        const buffer = await storage.readBuffer(source.fileLocation);
        const result = await extractPdfPageRangeText(buffer, sel.pageFrom, sel.pageTo);
        if (result && result.text) {
          parts.push(result.text);
          usedSources.push(source);
          continue;
        }
      } catch {
        // Fall through to the stored full-document text below rather than
        // dropping the source entirely over a page-range extraction hiccup.
      }
    }

    if (source.extractionStatus === "extracted" && source.extractedText) {
      parts.push(source.extractedText);
      usedSources.push(source);
    }
  }

  if (parts.length === 0) return { contextText: null, usedSources: [] };
  const combined = parts.join("\n\n---\n\n").slice(0, MAX_CONTEXT_CHARS_FOR_PROMPT);
  return { contextText: combined, usedSources };
}

async function getSchoolFormatTemplate(schoolId: string) {
  return prisma.schoolFormatTemplate.findUnique({
    where: { schoolId_appliesTo: { schoolId, appliesTo: "generation" } },
  });
}

// Applies the two presentation templates that need work beyond what the AI
// call itself produces - branding is a rendering concern (set from the
// school's row, never generated by the model), and Unsplash images are a
// separate best-effort fetch per slide after the AI returns the slide
// structure. No-op for every other outputType/template.
async function applyPresentationTemplateExtras(params: {
  content: string;
  outputType: GenerationOutputType;
  presentationTemplate?: PresentationTemplate;
  schoolId: string;
  topicId: string;
  topicName: string;
}): Promise<string> {
  if (params.outputType !== "presentation") return params.content;

  let parsed: { slides?: { title: string; bullets: string[]; imageUrl?: string }[]; [key: string]: unknown };
  try {
    parsed = JSON.parse(params.content);
  } catch {
    return params.content;
  }

  if (params.presentationTemplate === "school_format") {
    const school = await prisma.school.findUnique({
      where: { id: params.schoolId },
      select: { logoUrl: true, primaryColor: true, secondaryColor: true },
    });
    parsed.logoUrl = school?.logoUrl ?? null;
    parsed.primaryColor = school?.primaryColor ?? null;
    parsed.secondaryColor = school?.secondaryColor ?? null;
  }

  if (params.presentationTemplate === "more_visual" && Array.isArray(parsed.slides)) {
    for (let i = 0; i < parsed.slides.length; i++) {
      const slide = parsed.slides[i];
      try {
        const photo = await searchUnsplashPhoto(slide.title || params.topicName);
        if (!photo) continue;
        const buffer = await downloadImage(photo.url);
        const { location } = await storage.save(`presentations/${params.topicId}/${Date.now()}-slide-${i}.jpg`, buffer);
        slide.imageUrl = location;
      } catch (err) {
        // Best-effort - a slide with no image just falls back to the color
        // scheme in the viewer, doesn't fail the whole generation.
        console.error(`[generations] Unsplash image fetch failed for slide ${i}:`, err);
      }
    }
  }

  return JSON.stringify(parsed);
}

const VALID_OUTPUT_TYPES: GenerationOutputType[] = [
  "lesson_plan",
  "custom_activity_report",
  "flashcards",
  "presentation",
];
const VALID_MODES = ["plan", "generate"];
const VALID_PRESENTATION_TEMPLATES: PresentationTemplate[] = ["detailed", "instructional", "school_format", "more_visual"];
const VALID_PRESENTATION_COLOR_SCHEMES: PresentationColorScheme[] = ["indigo", "coral", "forest", "slate"];

interface CreateGenerationBody {
  outputType: GenerationOutputType;
  mode?: string;
  classCount?: number;
  minutesPerClass?: number;
  language?: string;
  customPrompt?: string;
  // Only meaningful when outputType is "presentation".
  presentationTemplate?: string;
  presentationColorScheme?: string;
  // Which context sources (and, for a long PDF, which page range) to ground
  // this generation in. Empty/omitted means "no context" - not "everything",
  // that implicit-everything behavior is what this field replaces.
  sources?: SourceSelection[];
}

interface UpdateGenerationBody {
  editedOutput: string;
}

const scoped = (app: FastifyInstance) => [app.authenticate, app.requireSchoolScope, requireRoles("teacher")];

export async function generationRoutes(app: FastifyInstance) {
  app.post<{ Params: { id: string }; Body: CreateGenerationBody }>(
    "/topics/:id/generations",
    { onRequest: scoped(app) },
    async (request, reply) => {
      const body = request.body ?? ({} as CreateGenerationBody);

      if (!body.outputType || !VALID_OUTPUT_TYPES.includes(body.outputType)) {
        return reply.code(400).send({
          data: null,
          error: { code: "validation_error", message: `outputType must be one of ${VALID_OUTPUT_TYPES.join(", ")}` },
        });
      }
      const mode = body.mode ?? "generate";
      if (!VALID_MODES.includes(mode)) {
        return reply.code(400).send({
          data: null,
          error: { code: "validation_error", message: `mode must be one of ${VALID_MODES.join(", ")}` },
        });
      }
      if (body.presentationTemplate && !VALID_PRESENTATION_TEMPLATES.includes(body.presentationTemplate as PresentationTemplate)) {
        return reply.code(400).send({
          data: null,
          error: { code: "validation_error", message: `presentationTemplate must be one of ${VALID_PRESENTATION_TEMPLATES.join(", ")}` },
        });
      }
      if (body.presentationColorScheme && !VALID_PRESENTATION_COLOR_SCHEMES.includes(body.presentationColorScheme as PresentationColorScheme)) {
        return reply.code(400).send({
          data: null,
          error: { code: "validation_error", message: `presentationColorScheme must be one of ${VALID_PRESENTATION_COLOR_SCHEMES.join(", ")}` },
        });
      }

      const topic = await prisma.topic.findFirst({
        where: { id: request.params.id, schoolId: request.schoolId },
        include: { classSection: true, contextSources: true },
      });
      if (!topic) {
        return reply.code(404).send({ data: null, error: { code: "not_found", message: "Topic not found" } });
      }

      const { contextText, usedSources } = await resolveSelectedContextText(topic.contextSources, body.sources ?? []);
      const formatTemplate = await getSchoolFormatTemplate(request.schoolId);

      const classCount = body.classCount ?? 1;
      const minutesPerClass = body.minutesPerClass ?? 45;
      if (classCount > 10 || minutesPerClass > 90) {
        return reply.code(400).send({
          data: null,
          error: { code: "validation_error", message: "classCount must be <= 10 and minutesPerClass <= 90" },
        });
      }

      const generationFeature = body.presentationTemplate === "more_visual" ? "presentation_visual" : "generation";
      if (!(await hasSufficientCredits(request.user.sub, getFeatureCost(generationFeature)))) {
        return reply.code(400).send({ data: null, error: { code: "insufficient_credits", message: "Not enough credits to generate this content" } });
      }

      const start = Date.now();
      let content: string;
      let model: string;
      let generationStatus = "succeeded";
      try {
        const result = await aiProvider.generateContent({
          topicName: topic.name,
          subject: topic.subject,
          board: topic.board,
          outputType: body.outputType,
          classCount,
          minutesPerClass,
          language: body.language ?? "English",
          customPrompt: body.customPrompt ?? null,
          classLabel: `${topic.classSection.className} ${topic.classSection.sectionName}`,
          contextText,
          schoolFormatInstructions: formatTemplate?.templateBody ?? null,
          presentationTemplate: body.presentationTemplate as PresentationTemplate | undefined,
          presentationColorScheme: body.presentationColorScheme as PresentationColorScheme | undefined,
        });
        content = await applyPresentationTemplateExtras({
          content: result.content,
          outputType: body.outputType,
          presentationTemplate: body.presentationTemplate as PresentationTemplate | undefined,
          schoolId: request.schoolId,
          topicId: topic.id,
          topicName: topic.name,
        });
        model = result.model;
      } catch (err) {
        app.log.error(err, "Generation failed");
        const failed = await prisma.generation.create({
          data: {
            topicId: topic.id,
            teacherUserId: request.user.sub,
            outputType: body.outputType,
            mode,
            classCount,
            minutesPerClass,
            language: body.language ?? "English",
            customPrompt: body.customPrompt ?? null,
            aiOutput: "",
            modelUsed: "unknown",
            generationStatus: "failed",
          },
          include: { contextSources: true },
        });
        return reply.code(201).send({ data: failed, meta: {} });
      }

      const generation = await prisma.generation.create({
        data: {
          topicId: topic.id,
          teacherUserId: request.user.sub,
          outputType: body.outputType,
          mode,
          classCount,
          minutesPerClass,
          language: body.language ?? "English",
          customPrompt: body.customPrompt ?? null,
          aiOutput: content,
          modelUsed: model,
          generationStatus,
          contextSources: { connect: usedSources.map((s) => ({ id: s.id })) },
          selectedSources: (body.sources ?? []) as unknown as object,
          schoolFormatTemplateId: formatTemplate?.id ?? null,
        },
        include: {
          contextSources: true,
          topic: { select: { name: true, subject: true, board: true, classSection: { select: { className: true, sectionName: true } } } },
        },
      });

      await logAiUsage({
        schoolId: request.schoolId,
        teacherUserId: request.user.sub,
        feature: generationFeature,
        model,
        durationMs: Date.now() - start,
      });

      return reply.code(201).send({ data: generation, meta: {} });
    }
  );

  app.get<{ Params: { id: string } }>("/generations/:id", { onRequest: scoped(app) }, async (request, reply) => {
    const generation = await prisma.generation.findFirst({
      where: { id: request.params.id, topic: { schoolId: request.schoolId } },
      include: {
        contextSources: true,
        topic: { select: { name: true, subject: true, board: true, classSection: { select: { className: true, sectionName: true } } } },
      },
    });
    if (!generation) {
      return reply.code(404).send({ data: null, error: { code: "not_found", message: "Generation not found" } });
    }
    return { data: generation, meta: {} };
  });

  app.patch<{ Params: { id: string }; Body: UpdateGenerationBody }>(
    "/generations/:id",
    { onRequest: scoped(app) },
    async (request, reply) => {
      const body = request.body ?? ({} as UpdateGenerationBody);
      if (!body.editedOutput || !body.editedOutput.trim()) {
        return reply.code(400).send({ data: null, error: { code: "validation_error", message: "editedOutput is required" } });
      }

      const generation = await prisma.generation.findFirst({
        where: { id: request.params.id, topic: { schoolId: request.schoolId } },
      });
      if (!generation) {
        return reply.code(404).send({ data: null, error: { code: "not_found", message: "Generation not found" } });
      }

      const updated = await prisma.generation.update({
        where: { id: generation.id },
        data: { editedOutput: body.editedOutput },
        include: { contextSources: true },
      });

      return { data: updated, meta: {} };
    }
  );

  app.post<{ Params: { id: string } }>("/generations/:id/retry", { onRequest: scoped(app) }, async (request, reply) => {
    const generation = await prisma.generation.findFirst({
      where: { id: request.params.id, topic: { schoolId: request.schoolId } },
      include: { topic: { include: { classSection: true, contextSources: true } }, contextSources: true },
    });
    if (!generation) {
      return reply.code(404).send({ data: null, error: { code: "not_found", message: "Generation not found" } });
    }

    // Reuse exactly what the original generation used - not the topic's
    // current full source list, so retrying doesn't silently pull in sources
    // added since. Generations created before source selection existed have
    // no selectedSources; fall back to the sources relation (whole documents,
    // no page ranges - that detail wasn't tracked pre-selection).
    const selection: SourceSelection[] =
      (generation.selectedSources as unknown as SourceSelection[] | null) ??
      generation.contextSources.map((s) => ({ contextSourceId: s.id }));
    const { contextText, usedSources } = await resolveSelectedContextText(generation.topic.contextSources, selection);
    const formatTemplate = await getSchoolFormatTemplate(request.schoolId);

    // Preserve the teacher's chosen presentation style across a retry rather
    // than silently reverting to the defaults - parsed from whatever this
    // generation last produced (falls back to defaults for pre-template rows).
    let presentationTemplate: PresentationTemplate | undefined;
    let presentationColorScheme: PresentationColorScheme | undefined;
    if (generation.outputType === "presentation") {
      try {
        const previous = JSON.parse(generation.editedOutput ?? generation.aiOutput) as {
          template?: PresentationTemplate;
          colorScheme?: PresentationColorScheme;
        };
        presentationTemplate = previous.template;
        presentationColorScheme = previous.colorScheme;
      } catch {
        // Ignore - defaults apply below.
      }
    }

    const retryFeature = presentationTemplate === "more_visual" ? "presentation_visual" : "generation";
    if (!(await hasSufficientCredits(request.user.sub, getFeatureCost(retryFeature)))) {
      return reply.code(400).send({ data: null, error: { code: "insufficient_credits", message: "Not enough credits to retry this generation" } });
    }

    const start = Date.now();
    const result = await aiProvider.generateContent({
      topicName: generation.topic.name,
      subject: generation.topic.subject,
      board: generation.topic.board,
      outputType: generation.outputType as GenerationOutputType,
      classCount: generation.classCount ?? 1,
      minutesPerClass: generation.minutesPerClass ?? 45,
      language: generation.language,
      customPrompt: generation.customPrompt,
      classLabel: `${generation.topic.classSection.className} ${generation.topic.classSection.sectionName}`,
      contextText,
      schoolFormatInstructions: formatTemplate?.templateBody ?? null,
      presentationTemplate,
      presentationColorScheme,
    });
    const content = await applyPresentationTemplateExtras({
      content: result.content,
      outputType: generation.outputType as GenerationOutputType,
      presentationTemplate,
      schoolId: request.schoolId,
      topicId: generation.topic.id,
      topicName: generation.topic.name,
    });
    const model = result.model;

    const updated = await prisma.generation.update({
      where: { id: generation.id },
      data: {
        aiOutput: content,
        modelUsed: model,
        generationStatus: "succeeded",
        editedOutput: null,
        contextSources: { set: usedSources.map((s) => ({ id: s.id })) },
        selectedSources: selection as unknown as object,
        schoolFormatTemplateId: formatTemplate?.id ?? null,
      },
      include: {
        contextSources: true,
        topic: { select: { name: true, subject: true, board: true, classSection: { select: { className: true, sectionName: true } } } },
      },
    });

    await logAiUsage({
      schoolId: request.schoolId,
      teacherUserId: request.user.sub,
      feature: retryFeature,
      model,
      durationMs: Date.now() - start,
    });

    return { data: updated, meta: {} };
  });

  // Publishing/unpublishing is what actually gates /student/materials - see
  // shareStatus on the Generation model. This is distinct from a future
  // "push to Communication Hub" delivery feature, which doesn't exist yet.
  app.post<{ Params: { id: string } }>("/generations/:id/publish", { onRequest: scoped(app) }, async (request, reply) => {
    const generation = await prisma.generation.findFirst({
      where: { id: request.params.id, topic: { schoolId: request.schoolId } },
    });
    if (!generation) {
      return reply.code(404).send({ data: null, error: { code: "not_found", message: "Generation not found" } });
    }
    if (generation.generationStatus !== "succeeded") {
      return reply.code(400).send({ data: null, error: { code: "validation_error", message: "Only a succeeded generation can be shared with students" } });
    }
    const updated = await prisma.generation.update({
      where: { id: generation.id },
      data: { shareStatus: "published", publishedAt: new Date() },
      include: { contextSources: true },
    });
    return { data: updated, meta: {} };
  });

  app.post<{ Params: { id: string } }>("/generations/:id/unpublish", { onRequest: scoped(app) }, async (request, reply) => {
    const generation = await prisma.generation.findFirst({
      where: { id: request.params.id, topic: { schoolId: request.schoolId } },
    });
    if (!generation) {
      return reply.code(404).send({ data: null, error: { code: "not_found", message: "Generation not found" } });
    }
    const updated = await prisma.generation.update({
      where: { id: generation.id },
      data: { shareStatus: "draft", publishedAt: null },
      include: { contextSources: true },
    });
    return { data: updated, meta: {} };
  });
}
