export const decorativeAssets = {
  heroBlob: require("../../assets/decorative/decor-hero-blob.png"),
  teacherHero: require("../../assets/decorative/decor-teacher-hero.png"),
  teacherLessonCat: require("../../assets/decorative/decor-teacher-lesson-cat.png"),
  teacherAssignment: require("../../assets/decorative/decor-teacher-assignment.png"),
  teacherSubmissions: require("../../assets/decorative/decor-teacher-submissions.png"),
  studioTeacher: require("../../assets/decorative/decor-studio-teacher.png"),
  sparklesLine: require("../../assets/decorative/decor-sparkles-line.png"),
  book: require("../../assets/decorative/decor-book.png"),
  cap: require("../../assets/decorative/decor-cap.png"),
  shield: require("../../assets/decorative/decor-shield.png"),
  idCard: require("../../assets/decorative/decor-id-card.png"),
  cornerFrame: require("../../assets/decorative/decor-corner-frame.png"),
  waveLines: require("../../assets/decorative/decor-wave-lines.png"),
  dotGrid: require("../../assets/decorative/decor-dot-grid.png"),
  stackedCards: require("../../assets/decorative/decor-stacked-cards.png"),
  starburst: require("../../assets/decorative/decor-starburst.png"),
  checkCircle: require("../../assets/decorative/decor-check-circle.png"),
  badgeRibbon: require("../../assets/decorative/decor-badge-ribbon.png"),
  chevronFlow: require("../../assets/decorative/decor-chevron-flow.png"),
  paperPlane: require("../../assets/decorative/decor-paper-plane.png"),
  ribbonBanner: require("../../assets/decorative/decor-ribbon-banner.png"),
} as const;
